# Generated by Django 5.1 on 2024-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoccupancy',
            name='sensor_name',
            field=models.CharField(default='Unknown Sensor', max_length=255),
        ),
    ]
